name: Django & Vue.js application CI/CD

on:
  push:
    branches:
      - rest_api_version_dont_merge
  pull_request:
    branches:
      - rest_api_version_dont_merge

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Django migrations
      run: python manage.py migrate
    - name: Lint with Flake8
      run: |
        pip install flake8
        flake8 .
    - name: Test Django with Pytest
      run: |
        pip install pytest-django
        pytest

  frontend:
    needs: backend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' 
    - name: Install frontend dependencies
      run: |
        cd /frontend/
        npm install
    - name: Lint Vue.js project
      run: |
        cd /frontend/
        npm run lint
    - name: Build Vue.js project
      run: |
        cd /frontend/
        npm run build
    - name: Test Vue.js project
      run: |
        cd /frontend/
        npm run test

  deploy:
    needs: frontend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/rest_api_version_dont_merge' && github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
    - name: Deploy Backend
      run: echo "Add your backend deployment commands here."
    - name: Deploy Frontend
      run: echo "Add your frontend deployment commands here."
